import { Metadata } from "next";
import React from "react";
import DriverLayout from "./layout/driverLayout";

export const metadata: Metadata = {
  title: "Driver Dashboard",
  description: "Generated by create next app",
};

const DriverDashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <DriverLayout>{children}</DriverLayout>
    </div>
  );
};

export default DriverDashboardLayout;
