import { Metadata } from "next";
import React from "react";
import AdminLayout from "./layout/adminLayout";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

const AdminDashboardLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div>
      <AdminLayout>{children}</AdminLayout>
    </div>
  );
};

export default AdminDashboardLayout;
